### ISSUE TITLE
Remove simple apps mention from repo description

### ISSUE THREAD

**Issue by johnnynoone** [FossifyOrg/Commons#14]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
Please replace the simple apps mention in repo description with a mention of Fossify (or whatever the final name is).

**To Reproduce**
Look at the repo description on GitHub. It says: "Some helper functions and shared resources to be used only by the simple apps suite."

**Device info (please complete the following information):**
Irrelevant.

**Comment by naveensingh** [comment]
Ok, done.
