### ISSUE TITLE
Improve selection of backup folder UX (Contacts, Calendar)

### ISSUE THREAD

**Issue by genodeftest** [FossifyOrg/Commons#36]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Commons/issues) or [closed](https://github.com/FossifyOrg/Commons/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Commons/discussions) or [closed](https://github.com/FossifyOrg/Commons/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Commons/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Steps to reproduce:
1. Open Fossify Contacts or Fossify Calendar
2. Open the three-dots-menu
3. Open _Settings_
4. Check _Enable automatic backups_
5. In the _Manage automatic backups_ dialog, click the path under _Folder_
6. Navigate to and select an existing folder (e.g. `Internal > Backups > Contacts` in my case)
7. Confirm folder selection by clicking _OK_
8. In the dialog _Confirm folder access_, confirm with _OK_
9. In the parent of the backup folder (`Internal > Backups` in my case), click _Use this folder_
10. When asked to allow contacts (or calendar) to access files in the folder, confirm with _Allow_

[Video/screencast](https://github.com/FossifyOrg/Commons/assets/934401/f2e28082-1758-4242-b99f-08a0d39b7fea)

#### Expected behavior
I expect to only select a single folder, as I'm only storing backups to a single folder. In other words, it would be nice to only have steps 6/7 OR 8/9/10.
Also, in step 9, I expect to give Fossify Contacts/Calendar access only to the backup directory (`Internal > Backups > Contacts` in my case), not to its parent.

#### Actual behavior
I am asked for locations twice, first with a Fossify dialog, then with a system dialog.
I have to give Fossify apps permissions to the backup directory's parent (`Internal > Backups` in my case).

### Additional information

I'm not entirely sure whether this is a bug or a missing feature, so I've reported it as feature request. Please feel free to change it to bug if that is more suitable.

This is **not** a duplicate of FossifyOrg/Calendar#101. In contrast to that issue, I'm able to select the folder, I just need to do it twice (once with app's own dialog, once with system dialog).

A similar issue has been reported by @mpldr to SimpleMobileTools before (SimpleMobileTools/Simple-Contacts#1064):
> The current DIY filepicker has some limitations, biggest of which is that you can't add existing locations. I keep my Backups in `Internal/Backups/[App]`, which is synced via syncthing. This works quite well for everything _except_ the most important stuff (contacts, calendars, notes).
> 
> Would it be possible to use the system file picker for choosing the location instead?

### Affected app version

Fossify Calendar 1.0.2 (from GitHub release page or F-Droid, does not seem to matter)
Fossify Contacts 1.0.1 (from GitHub release page or F-Droid, does not seem to matter)

### Affected Android/Custom ROM version

Android 13, patchlevel 2024-01-05 (FP4.TP29.C.0101.20240121)

### Affected device model

Fairphone 4

**Comment by Aga-C** [comment]
Please raise issues regarding all apps in https://github.com/FossifyOrg/General-Discussion/issues.
